//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallePedido
    {
        public int DetallePedidoId { get; set; }
        public Nullable<int> PedidoId { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<int> ProductoId { get; set; }
        public Nullable<decimal> ValorTotal { get; set; }
        public Nullable<short> Estado { get; set; }
    
        public virtual Pedido Pedido { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
