//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleiIngreso
    {
        public int DetalleIngresoId { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> PrecioUnitario { get; set; }
        public Nullable<decimal> PrecioFinal { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> ProductoId { get; set; }
        public Nullable<int> IngresoEgresoId { get; set; }
        public Nullable<short> Estado { get; set; }
    
        public virtual IngresoEgreso IngresoEgreso { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
