//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngresoEgreso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IngresoEgreso()
        {
            this.DetalleiIngreso = new HashSet<DetalleiIngreso>();
        }
    
        public int IngresoEgresoId { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> TipoTransaccionId { get; set; }
        public Nullable<short> Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleiIngreso> DetalleiIngreso { get; set; }
        public virtual TipoTransaccion TipoTransaccion { get; set; }
    }
}
