//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infra.DataAccess
{
    using Dominio.Model.Entities;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BdCafeteriaEntities1 : DbContext
    {
        public BdCafeteriaEntities1()
            : base("name=BdCafeteriaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<DetalleiIngreso> DetalleiIngreso { get; set; }
        public virtual DbSet<IngresoEgreso> IngresoEgreso { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<TipoTransaccion> TipoTransaccion { get; set; }
    }
}
